---
- name: install essential packages (this may take a while)
  pacman: name="{{ item }}"
  with_items:
  - ibus
  - mesa
  - xf86-video-intel
  - xorg-xinput
  - xorg-xrandr
  tags:
  - xorg

- name: remove lightdm-webkit2-greeter if installed
  pacman:
    name: lightdm-webkit2-greeter
    state: absent
  register: lightdmwebkit
  tags:
  - xorg

- name: install lightdm-gtk-greeter as replacement
  pacman: name=lightdm-gtk-greeter
  when: lightdmwebkit.changed
  tags:
  - xorg

- name: set lightdm-gtk-greeter as default lightdm greeter
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: lightdm-webkit2-greeter
    replace: lightdm-gtk-greeter
  when: lightdmwebkit.changed
  tags:
  - xorg